### ISSUE TITLE
Source of magic css values

### ISSUE THREAD

**Issue by jackinloadup** [gnome-integration-team/firefox-gnome#188]
I'm curious where values used in the following example are coming from.

``` css
menubar > menu[open] {
  color: MenuText;
  background-color: Menu;
  border-radius: 3px 3px 0 0;
}
```

Values like Menu and MenuText. Is there a list of theses magic values anywhere?
