### ISSUE TITLE
Notifications look meh.

### ISSUE THREAD

**Issue by 0rAX0** [gnome-integration-team/firefox-gnome#256]
I think that we should deal with those pesky notifications as well while we're refreshing everything. The current ones are annoying me so much, look at this:

![screenshot from 2014-06-03 11 39 59](https://cloud.githubusercontent.com/assets/1044370/3159041/a1687aa4-eb0b-11e3-8baa-ff51e53aff77.png)

I have a working style, but it needs some fixes, it gives this: 

![screenshot from 2014-06-03 11 42 14](https://cloud.githubusercontent.com/assets/1044370/3159048/bff421e4-eb0b-11e3-9e3a-52ebe960c45a.png)

Code (Stylish):

``` CSS
.messageText
 {
  cursor: default;
  margin-top: 1px;
  margin-bottom: 2px;
  -moz-margin-start: 6px;
  -moz-margin-end: 5px;
  color: rgba(255,255,255,0.9);
  text-shadow: 0 1px 0 rgba(0,0,0,0.3); 
  font-weight: bold;
}
notification{
  border-bottom: 1px solid rgba(0,0,0,0.2);
  background-color: rgba(25,0,255,0.5);
  box-shadow: 0 -1px rgba(255,255,255,0.15) inset;
}

notification > button,
notification toolbarbutton {
  margin-top: 0;
  margin-bottom: 0;
  -moz-appearance: none;
  background: transparent !important ;
  border-radius: 3px;
  border-color: rgba(255,255,255,0.5);
  padding: 3px;
  box-shadow: none;
  color: white;
  transition-property: color, border, box-shadow, background;
  transition-duration: 200ms;
}

.notification-button.notification-button-default:hover,
notification .messageCloseButton:hover {
  background: rgba(255,255,255,0.5) !important ;
  border-color: rgba(255,255,255,0.5) !important;
}

notification .messageCloseButton {
  background: transparent !important;
  border: 1px solid transparent !important;
  list-style-image: url(chrome://symbolic-icons/skin/close_white.svg);
}
```

But it's still buggy and misses proper design and other things. I can do it but I need help ... is there a list somewhere of all possible default notifications?

What do you think, can we do it?
