### ISSUE TITLE
Fix support for "Tree Style Tab"

### ISSUE THREAD

**Issue by rompe** [gnome-integration-team/firefox-gnome#313]
While support for this extension ( https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/ ) has been introduced with #81 and worked smooth for years, it has been broken since 33.1. You see the following issues:
![bildschirmfoto vom 2015-01-21 07 07 10](https://cloud.githubusercontent.com/assets/1234776/5831984/6212fb70-a13d-11e4-8fbc-27df206e4fb0.png)
1. The active, pinned tab overlaps the normal tab below.
2. Tab labels are centered, making it very hard to recognize the tree structure. (This one is the show stopper for me.)
![bildschirmfoto vom 2015-01-21 07 26 24](https://cloud.githubusercontent.com/assets/1234776/5832059/2ae98586-a13f-11e4-80a8-034285ffe25e.png)
3. Styling of active and hovered tabs looks a bit bulky.

Now that 32.1 doesn't work anymore with current Firefox it would be great if support for this extension could be restored.

**Comment by rompe** [comment]
For the time being, my workaround for the centered tab labels is to comment out this line in browser.css:
    -moz-binding: url(chrome://browser/skin/gnomeBindings.xml#label-center);

**Comment by synapsos** [comment]
To temporarily fix the other issues, use one of the other themes in TST
settings (flat, vertigo). I'm working on a reworked theme integration.
Question: Should "Close" buttons be visible on all tabs?

**Comment by rompe** [comment]
I'm used to having close buttons on all tabs. They may be dimmed a bit on inactive tabs, but having them everywhere eases closing tabs without having to activate them or using the context menu.

**Comment by rompe** [comment]
Sidebar style looks great in conjunction with the -moz-binding hack, thanks for this hint!

Regarding the visibility of close buttons, the current behavior (tab close button is visible on active tab only but gets visible on other tabs when hovering) is perfect for me. This way, the interface doesn't get cluttered but you can close any tab just one click.

**Comment by seleznev** [comment]
@rompe, I think following userstyle can be used as temporary solution (it's better then editing the sources):

```CSS
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");

@-moz-document url("chrome://browser/content/browser.xul") {

  #TabsToolbar.treestyletab-tabbar-toolbar[orient="vertical"] .tab-spacer {
    display: none;
  }

}
```

@synapsos, please notice me if you will need any help.
