### ISSUE TITLE
Help with stylish

### ISSUE THREAD

**Issue by Hombremaledicto** [gnome-integration-team/firefox-gnome#326]
Hi,

First of all, thank you for this great theme. I'm actually using it on my [Uber Weird kde desktop](http://hombremaledicto.deviantart.com/art/Scrot-from-my-notebook-530319253), and i find it breath taking!
I'd like to mod it a little though, but i need to ask your help with:

- Remove the blue line at the bottom of the active tab 
- Code for tabs height
- If you can link me the CSS files for tabs close button and deco buttons (for htitle extension - by the way: is the placement of buttons settled from this theme or directly from htitle?)

So far i'm using stylish for the purpose, but in the future i might mod the source directly.

Thank you in advance, and again thank you for all the great work on FF !

P.s. As it looks [so far](http://postimg.org/image/6sain0ja7/)

**Comment by seleznev** [comment]
> Remove the blue line at the bottom of the active tab.

* https://github.com/gnome-integration-team/firefox-gnome/blob/master/theme/shared/browser/browser.css#L2498

* https://github.com/gnome-integration-team/firefox-gnome/blob/master/theme/shared/browser/browser.css#L2536


```CSS
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");

@-moz-document url("chrome://browser/content/browser.xul") {

  .tab-background-middle {
    -moz-border-bottom-colors: transparent !important;
  }

  .tab-background-start,
  .tab-background-end {
    background-image: none !important;
  }

}
```

![screenshot from 2015-05-03 11-35-28](https://cloud.githubusercontent.com/assets/1687481/7443821/23c3ff98-f180-11e4-9a4e-2c20921dfa53.png)

(If you need 1px bottom border, just set border width to 1px and set right color)

---

> Code for tabs height

Be careful with this part. Not sure that it's all.

* https://github.com/gnome-integration-team/firefox-gnome/blob/master/theme/shared/browser/browser.css#L2415

* https://github.com/gnome-integration-team/firefox-gnome/blob/master/theme/shared/browser/browser.css#L2576

```CSS
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");

@-moz-document url("chrome://browser/content/browser.xul") {

  #tabbrowser-tabs,
  .tabbrowser-tab > .tab-stack {
    min-height: 0 !important;
  }

}
```

---

> If you can link me the CSS files for tabs close button and deco buttons (for htitle extension - by the way: is the placement of buttons settled from this theme or directly from htitle?)

> is the placement of buttons settled from this theme

This.

> tabs close button

* https://github.com/gnome-integration-team/firefox-gnome/blob/master/theme/shared/browser/browser.css#L2707

> deco buttons

* https://github.com/gnome-integration-team/firefox-gnome/blob/master/theme/shared/browser/browser.css#L1151

* https://github.com/gnome-integration-team/firefox-gnome/blob/master/theme/shared/browser/browser.css#L1190

If you need any additional information, please tell me.
