### ISSUE TITLE
Tree Style Tab extension dark theme not working

### ISSUE THREAD

**Issue by deathlyfrantic** [gnome-integration-team/firefox-gnome#390]
The Tree Style Tab extension doesn't respect the GTK global dark theme. I've managed to fix this with a userstyle that includes these:

``` css
#TabsToolbar.treestyletab-tabbar-toolbar[orient="vertical"]:not([treestyletab-style]) {
    background-color: inherit !important;
}

#TabsToolbar.treestyletab-tabbar-toolbar[orient="vertical"]:not([treestyletab-style]) .tabbrowser-tab, 
#TabsToolbar.treestyletab-tabbar-toolbar[orient="vertical"]:not([treestyletab-style]) .tabbrowser-tab > .tab-stack {
    color: inherit !important;
}
```

So I am thinking this probably is probably just that the extension didn't get updated when moving to the "new" dark-theme configuration (i.e. the process that involved removing the `extensions.gnome-theme-tweak.dark-variant` bit). (If that is the case, the AdBlock Plus extension probably doesn't work right either, as it also uses the `[darkvariant]` CSS selector. I don't use ABP so I haven't tested.)

FWIW I am using Firefox 43.0.1 (GTK3) on Arch. I'd be glad to provide any other information that would be helpful. Thanks!
