### ISSUE TITLE
Bookmarks

### ISSUE THREAD

**Issue by vendforce** [gnome-integration-team/firefox-gnome#398]
![screenshot from 2016-04-13 14-03-16](https://cloud.githubusercontent.com/assets/15267883/14494030/9888bc9a-0180-11e6-9242-c90dfedb5ddb.png)
Can you please add option to move the bookmarks bar to the bottom 

According to the picture is says it has option for tabs on top which isnt in the options

**Comment by synapsos** [comment]
If you just want the bookmarks bar below the tabs bar, I made a userstyle you can use with the [Stylish addon](https://addons.mozilla.org/firefox/addon/stylish/). Putting tabs on top of everything is no longer supported by our theme.

```css
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");
@-moz-document url("chrome://browser/content/browser.xul") {

  #navigator-toolbox {
    /* allow repositioning of children */
    position: relative;
  }
  
  #PersonalToolbar[collapsed="false"] {
    position: absolute;
    top: 72px;
    width: 100%;
  }

  #TabsToolbar {
    margin-bottom: 34px;
  }
}
```

Please tell me if this works for you!
